name: Envoi Mots Anglais

on:
  schedule:
    # 05:00 UTC correspond à 06:00 heure de Paris (en hiver)
    - cron: '0 5 * * *'
  workflow_dispatch: # Permet de tester manuellement

jobs:
  send_words:
    runs-on: ubuntu-latest
    steps:
      - name: Récupérer le code
        uses: actions/checkout@v4

      - name: Installer Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Installer les dépendances
        run: pip install requests nltk

      - name: Exécuter le script
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: python script.py
      - name: Cache NLTK
        uses: actions/cache@v4
        with:
          path: ~/nltk_data
          key: nltk-wordnet
      - name: Commit used words
        run: |
          git config user.name "lumiere-MULAGWA"
          git config user.email "21mb358@esisalama.org"
          git add used_words.json
          git commit -m "chore: update used words" || exit 0
          git push


